name: Deploy Static Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        
      - name: 📝 Update Version
        run: |
          CURRENT_DATE=$(date +%Y%m%d-%H%M)
          sed -i "s/const GAME_VERSION = '.*'/const GAME_VERSION = '2.1.$CURRENT_DATE'/" script.js
          echo "✅ Version updated to: 2.1.$CURRENT_DATE"
          
      - name: 📦 Prepare Files
        run: |
          echo "📁 Files ready for deployment:"
          ls -la
          
      - name: ✅ Success
        run: echo "🎉 Game files updated! Enable GitHub Pages manually in Settings."
